/**
 * C++ code generator for JUCE WebView2 bindings
 * Generates copy-paste ready C++ snippets for header and constructor
 */

import type { ElementConfig } from '../../types/elements'
import { toKebabCase, toCamelCase } from './utils'
import { isInteractiveElement } from './validators'

// ============================================================================
// C++ Code Generator
// ============================================================================

/**
 * Generate C++ relay and attachment code for JUCE WebView2
 * Organized by destination: header declarations, then constructor initialization
 *
 * @param elements - Array of element configurations
 * @returns C++ code snippets as string
 *
 * @example
 * const cppCode = generateCPP(elements)
 * // Copy header section to PluginEditor.h
 * // Copy constructor section to PluginEditor.cpp
 */
export function generateCPP(elements: ElementConfig[]): string {
  const interactiveElements = elements.filter(isInteractiveElement)

  if (interactiveElements.length === 0) {
    return `// ============================================================================
// JUCE WebView2 Bindings
// Generated by VST3 WebView UI Designer
// ============================================================================

// No interactive elements found
// Add knobs, sliders, or buttons to generate bindings
`
  }

  // Generate header declarations
  const headerDeclarations = interactiveElements
    .map((element) => {
      const varName = toCamelCase(element.name)
      const relayType = getRelayType(element)
      const attachmentType = getAttachmentType(element)

      return `std::unique_ptr<juce::${relayType}> ${varName}Relay;
std::unique_ptr<juce::${attachmentType}> ${varName}Attachment;`
    })
    .join('\n')

  // Generate constructor initialization
  const constructorInits = interactiveElements
    .map((element) => {
      const varName = toCamelCase(element.name)
      const id = toKebabCase(element.name)
      const relayType = getRelayType(element)
      const attachmentType = getAttachmentType(element)

      // Check if parameterId is defined
      const hasParameterId = element.parameterId && element.parameterId.trim() !== ''

      if (hasParameterId) {
        // Full attachment code
        return `// ${element.name} (${element.type})
${varName}Relay = std::make_unique<juce::${relayType}>(*webView, "${id}");
${varName}Attachment = std::make_unique<juce::${attachmentType}>(
    *processorRef.parameters.getParameter("${element.parameterId}"),
    *${varName}Relay,
    nullptr  // undoManager
);`
      } else {
        // Missing parameterId - generate TODO comment
        return `// ${element.name} (${element.type})
${varName}Relay = std::make_unique<juce::${relayType}>(*webView, "${id}");
// TODO: Set parameterId in designer for this element
// ${varName}Attachment = std::make_unique<juce::${attachmentType}>(
//     *processorRef.parameters.getParameter("YOUR_PARAMETER_ID"),
//     *${varName}Relay,
//     nullptr
// );`
      }
    })
    .join('\n\n')

  // Assemble complete C++ output
  return `// ============================================================================
// JUCE WebView2 Bindings
// Generated by VST3 WebView UI Designer
// ============================================================================

// ============================================================================
// Header Declarations (add to PluginEditor.h private section)
// ============================================================================

${headerDeclarations}

// ============================================================================
// Constructor Initialization (add to PluginEditor constructor after webView setup)
// ============================================================================

${constructorInits}
`
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get JUCE relay class name for element type
 *
 * @param element - Element configuration
 * @returns JUCE relay class name (without juce:: prefix)
 */
function getRelayType(element: ElementConfig): string {
  switch (element.type) {
    case 'knob':
    case 'slider':
      return 'WebSliderRelay'
    case 'button':
      return 'WebToggleButtonRelay'
    default:
      // Should never reach here due to isInteractiveElement filter
      return 'WebSliderRelay'
  }
}

/**
 * Get JUCE parameter attachment class name for element type
 *
 * @param element - Element configuration
 * @returns JUCE attachment class name (without juce:: prefix)
 */
function getAttachmentType(element: ElementConfig): string {
  switch (element.type) {
    case 'knob':
    case 'slider':
      return 'WebSliderParameterAttachment'
    case 'button':
      return 'WebToggleButtonParameterAttachment'
    default:
      // Should never reach here due to isInteractiveElement filter
      return 'WebSliderParameterAttachment'
  }
}
