/**
 * C++ code generator for JUCE WebView2 bindings
 * Generates copy-paste ready C++ snippets for header and constructor
 */

import type { ElementConfig } from '../../types/elements'
import { isInteractiveElement } from './validators'

// ============================================================================
// C++ Code Generator
// ============================================================================

/**
 * Generate C++ code snippets for JUCE WebView2 with native function bindings
 * Uses event-based invocation pattern with withNativeFunction()
 *
 * @param elements - Array of element configurations
 * @returns C++ code snippets as string
 *
 * @example
 * const cppCode = generateCPP(elements)
 * // Copy to PluginEditor constructor, BEFORE goToURL()
 */
export function generateCPP(elements: ElementConfig[]): string {
  const interactiveElements = elements.filter(isInteractiveElement)

  // Extract unique parameter IDs
  const params = interactiveElements
    .filter((el) => el.parameterId && el.parameterId.trim() !== '')
    .map((el) => el.parameterId as string)
  const uniqueParams = [...new Set(params)]

  if (uniqueParams.length === 0) {
    return `// ============================================================================
// C++ Code Snippets for PluginEditor.cpp
// Generated by VST3 WebView UI Designer
// ============================================================================

// No interactive elements with parameter bindings found
// Add knobs, sliders, or buttons with parameterId set to generate bindings
`
  }

  // Generate parameter ID list for reference
  const paramIdComments = uniqueParams.map((id) => `// - "${id}"`).join('\n')

  return `// ============================================================================
// C++ Code Snippets for PluginEditor.cpp
// Generated by VST3 WebView UI Designer
// ============================================================================

// Add these native function registrations to your WebView options
// In PluginEditor constructor, BEFORE goToURL():

webView = std::make_unique<juce::WebBrowserComponent>(
    juce::WebBrowserComponent::Options{}
        .withNativeIntegrationEnabled()

        // Parameter setter (fire-and-forget from JavaScript)
        .withNativeFunction("setParameter",
            [this](const juce::Array<juce::var>& args, auto complete) {
                if (args.size() >= 2) {
                    auto paramId = args[0].toString();
                    auto value = static_cast<float>(args[1]);

                    if (auto* param = processorRef.apvts.getParameter(paramId)) {
                        param->setValueNotifyingHost(value);
                    }
                }
                complete(juce::var());
            })

        // Parameter getter (returns current value)
        .withNativeFunction("getParameter",
            [this](const juce::Array<juce::var>& args, auto complete) {
                if (args.size() >= 1) {
                    auto paramId = args[0].toString();

                    if (auto* param = processorRef.apvts.getParameter(paramId)) {
                        complete(param->getValue());
                        return;
                    }
                }
                complete(0.0f);
            })

        // Begin automation gesture (for DAW recording)
        .withNativeFunction("beginGesture",
            [this](const juce::Array<juce::var>& args, auto complete) {
                if (args.size() >= 1) {
                    auto paramId = args[0].toString();

                    if (auto* param = processorRef.apvts.getParameter(paramId)) {
                        param->beginChangeGesture();
                    }
                }
                complete(juce::var());
            })

        // End automation gesture
        .withNativeFunction("endGesture",
            [this](const juce::Array<juce::var>& args, auto complete) {
                if (args.size() >= 1) {
                    auto paramId = args[0].toString();

                    if (auto* param = processorRef.apvts.getParameter(paramId)) {
                        param->endChangeGesture();
                    }
                }
                complete(juce::var());
            })

        .withBackend(juce::WebBrowserComponent::Options::Backend::webview2)
        // ... other options (withResourceProvider, etc.)
);

// ============================================================================
// Your parameter IDs from the UI:
// ============================================================================
${paramIdComments}

// Make sure these match your APVTS parameter IDs in PluginProcessor.cpp!
`
}

