/**
 * Generate README documentation for JUCE WebView2 export bundle
 */

import { ElementConfig } from '../../types/elements'
import { formatKnownIssuesMarkdown } from './knownIssues'

interface DocumentationOptions {
  projectName: string
  elements: ElementConfig[]
  includeHtmlPreview: boolean
  includeJuceBundle: boolean
}

export function generateReadme(options: DocumentationOptions): string {
  const { projectName, elements, includeHtmlPreview, includeJuceBundle } = options

  const controlCount = {
    knobs: elements.filter(e => e.type === 'knob').length,
    sliders: elements.filter(e => e.type === 'slider').length,
    buttons: elements.filter(e => e.type === 'button').length,
    meters: elements.filter(e => e.type === 'meter').length,
    labels: elements.filter(e => e.type === 'label').length,
    images: elements.filter(e => e.type === 'image').length,
  }

  // Build contents section
  const contentsParts = []
  if (includeHtmlPreview) {
    contentsParts.push('- `index.html` - Main HTML structure')
    contentsParts.push('- `styles.css` - Element styles and layout')
    contentsParts.push('- `components.js` - UI component rendering')
    contentsParts.push('- `bindings.js` - JUCE WebSliderRelay bindings')
  }
  if (includeJuceBundle) {
    contentsParts.push('- `bindings.cpp` - C++ boilerplate for JUCE integration')
  }
  contentsParts.push('- `README.md` - This documentation')

  // Build parameter mapping table
  const parameterRows = elements
    .filter(e => e.parameterId)
    .map(e => `| ${e.name} | \`${e.parameterId}\` | ${e.type} |`)

  const parameterTable = parameterRows.length > 0
    ? parameterRows.join('\n')
    : '| (none) | - | - |'

  // Build README sections
  const sections = [
    `# ${projectName} - WebView UI Export`,
    '',
    'Generated by VST3 WebView UI Designer',
    '',
    '## Contents',
    '',
    'This export bundle contains:',
    '',
    contentsParts.join('\n'),
    '',
    '## UI Summary',
    '',
    '| Element Type | Count |',
    '|-------------|-------|',
    `| Knobs | ${controlCount.knobs} |`,
    `| Sliders | ${controlCount.sliders} |`,
    `| Buttons | ${controlCount.buttons} |`,
    `| Meters | ${controlCount.meters} |`,
    `| Labels | ${controlCount.labels} |`,
    `| Images | ${controlCount.images} |`,
    '',
    '## Integration Steps',
    '',
    '### 1. Copy Files to Your JUCE Project',
    '',
    "Copy the web files to your JUCE project's resource folder:",
    '',
    '```',
    'YourPlugin/',
    '├── Source/',
    '│   ├── PluginProcessor.cpp',
    '│   ├── PluginEditor.cpp',
    '│   └── WebUI/           <- Create this folder',
    '│       ├── index.html',
    '│       ├── styles.css',
    '│       ├── components.js',
    '│       └── bindings.js',
    '```',
    '',
    '### 2. Add WebView to Your Editor',
    '',
    'In your PluginEditor.h:',
    '',
    '```cpp',
    '#include <juce_gui_extra/juce_gui_extra.h>',
    '',
    'class YourPluginEditor : public juce::AudioProcessorEditor',
    '{',
    'public:',
    '    YourPluginEditor(YourPluginProcessor&);',
    '    ~YourPluginEditor() override;',
    '',
    '    void resized() override;',
    '',
    'private:',
    '    std::unique_ptr<juce::WebBrowserComponent> webView;',
    '    YourPluginProcessor& processor;',
    '};',
    '```',
    '',
    '### 3. Initialize WebView',
    '',
    'In your PluginEditor.cpp:',
    '',
    '```cpp',
    'YourPluginEditor::YourPluginEditor(YourPluginProcessor& p)',
    '    : AudioProcessorEditor(&p), processor(p)',
    '{',
    '    // Set editor size to match your design canvas',
    '    setSize(800, 600);',
    '',
    '    // Create WebView with dark background to prevent flash',
    '    juce::WebBrowserComponent::Options options;',
    '    options = options.withBackgroundColour(juce::Colour(0x1a, 0x1a, 0x1a));',
    '',
    '    webView = std::make_unique<juce::WebBrowserComponent>(options);',
    '    addAndMakeVisible(*webView);',
    '',
    '    // Load the UI from resources',
    '    auto resourceDir = juce::File::getSpecialLocation(',
    '        juce::File::currentApplicationFile',
    '    ).getChildFile("Contents/Resources/WebUI");',
    '',
    '    webView->goToURL(resourceDir.getChildFile("index.html").getFullPathName());',
    '}',
    '',
    'void YourPluginEditor::resized()',
    '{',
    '    webView->setBounds(getLocalBounds());',
    '}',
    '```',
    '',
    '### 4. Connect Parameter Bindings',
    '',
    includeJuceBundle
      ? 'See `bindings.cpp` for the C++ relay setup code.'
      : "You'll need to implement WebSliderRelay bindings manually.",
    '',
    'Each control with a `data-parameter-id` attribute needs a corresponding relay:',
    '',
    '```cpp',
    '// For each knob/slider:',
    'webSliderRelay->registerSlider("parameterName", [this](float value) {',
    '    processor.getParameters().getParameter("parameterName")->setValueNotifyingHost(value);',
    '});',
    '```',
    '',
    '### 5. Build and Test',
    '',
    '1. Add the WebUI folder to your JUCE project resources',
    '2. Build your plugin',
    '3. Load in a DAW and verify controls respond',
    '',
    '## Parameter Mapping',
    '',
    'The following elements have parameter bindings:',
    '',
    '| Element | Parameter ID | Type |',
    '|---------|--------------|------|',
    parameterTable,
    '',
    formatKnownIssuesMarkdown(),
    '',
    '## Troubleshooting',
    '',
    "### Controls don't respond",
    '- Verify parameter IDs match between HTML and C++',
    '- Check browser console for JavaScript errors',
    '- Ensure WebSliderRelay is properly initialized',
    '',
    "### UI doesn't appear",
    '- Check file paths are correct',
    '- Verify WebView2 runtime is installed (Windows)',
    '- Check JUCE WebBrowserComponent is added and visible',
    '',
    '### Visual glitches',
    '- Set WebView background color to match your CSS',
    '- Use `font-display: swap` for custom fonts',
    '- Avoid complex CSS animations during parameter updates',
    '',
    '---',
    '',
    '*Generated by [VST3 WebView UI Designer](https://github.com/your-repo)*',
  ]

  return sections.join('\n')
}
