/**
 * Generate README documentation for JUCE WebView2 export bundle
 */

import { ElementConfig } from '../../types/elements'
import { formatKnownIssuesMarkdown } from './knownIssues'

interface DocumentationOptions {
  projectName: string
  elements: ElementConfig[]
  includeHtmlPreview: boolean
  includeJuceBundle: boolean
}

export function generateReadme(options: DocumentationOptions): string {
  const { projectName, elements, includeHtmlPreview, includeJuceBundle } = options

  const controlCount = {
    knobs: elements.filter(e => e.type === 'knob').length,
    sliders: elements.filter(e => e.type === 'slider').length,
    buttons: elements.filter(e => e.type === 'button').length,
    meters: elements.filter(e => e.type === 'meter').length,
    labels: elements.filter(e => e.type === 'label').length,
    images: elements.filter(e => e.type === 'image').length,
  }

  // Extract string literals with backticks to avoid template literal issues
  const htmlPreviewFiles = includeHtmlPreview
    ? '- `index.html` - Main HTML structure\n- `styles.css` - Element styles and layout\n- `components.js` - UI component rendering\n- `bindings.js` - JUCE WebSliderRelay bindings\n'
    : ''

  const juceBundleFiles = includeJuceBundle
    ? '- `bindings.cpp` - C++ boilerplate for JUCE integration\n'
    : ''

  const bindingsText = includeJuceBundle
    ? 'See `bindings.cpp` for the C++ relay setup code.'
    : "You'll need to implement WebSliderRelay bindings manually."

  const parameterRows = elements
    .filter(e => e.parameterId)
    .map(e => '| ' + e.name + ' | `' + e.parameterId + '` | ' + e.type + ' |')
    .join('\n') || '| (none) | - | - |'

  let readme = '# ' + projectName + ' - WebView UI Export\n\n'
  readme += 'Generated by VST3 WebView UI Designer\n\n'
  readme += '## Contents\n\n'
  readme += 'This export bundle contains:\n\n'
  readme += htmlPreviewFiles
  readme += juceBundleFiles
  readme += '- `README.md` - This documentation\n\n'
  readme += '## UI Summary\n\n'
  readme += '| Element Type | Count |\n'
  readme += '|-------------|-------|\n'
  readme += '| Knobs | ' + controlCount.knobs + ' |\n'
  readme += '| Sliders | ' + controlCount.sliders + ' |\n'
  readme += '| Buttons | ' + controlCount.buttons + ' |\n'
  readme += '| Meters | ' + controlCount.meters + ' |\n'
  readme += '| Labels | ' + controlCount.labels + ' |\n'
  readme += '| Images | ' + controlCount.images + ' |\n\n'
  readme += '## Integration Steps\n\n'
  readme += '### 1. Copy Files to Your JUCE Project\n\n'
  readme += 'Copy the web files to your JUCE project\'s resource folder:\n\n'
  readme += '```\n'
  readme += 'YourPlugin/\n'
  readme += '├── Source/\n'
  readme += '│   ├── PluginProcessor.cpp\n'
  readme += '│   ├── PluginEditor.cpp\n'
  readme += '│   └── WebUI/           <- Create this folder\n'
  readme += '│       ├── index.html\n'
  readme += '│       ├── styles.css\n'
  readme += '│       ├── components.js\n'
  readme += '│       └── bindings.js\n'
  readme += '```\n\n'
  readme += '### 2. Add WebView to Your Editor\n\n'
  readme += 'In your PluginEditor.h:\n\n'
  readme += '```cpp\n'
  readme += '#include <juce_gui_extra/juce_gui_extra.h>\n\n'
  readme += 'class YourPluginEditor : public juce::AudioProcessorEditor\n'
  readme += '{\n'
  readme += 'public:\n'
  readme += '    YourPluginEditor(YourPluginProcessor&);\n'
  readme += '    ~YourPluginEditor() override;\n\n'
  readme += '    void resized() override;\n\n'
  readme += 'private:\n'
  readme += '    std::unique_ptr<juce::WebBrowserComponent> webView;\n'
  readme += '    YourPluginProcessor& processor;\n'
  readme += '};\n'
  readme += '```\n\n'
  readme += '### 3. Initialize WebView\n\n'
  readme += 'In your PluginEditor.cpp:\n\n'
  readme += '```cpp\n'
  readme += 'YourPluginEditor::YourPluginEditor(YourPluginProcessor& p)\n'
  readme += '    : AudioProcessorEditor(&p), processor(p)\n'
  readme += '{\n'
  readme += '    // Set editor size to match your design canvas\n'
  readme += '    setSize(800, 600);\n\n'
  readme += '    // Create WebView with dark background to prevent flash\n'
  readme += '    juce::WebBrowserComponent::Options options;\n'
  readme += '    options = options.withBackgroundColour(juce::Colour(0x1a, 0x1a, 0x1a));\n\n'
  readme += '    webView = std::make_unique<juce::WebBrowserComponent>(options);\n'
  readme += '    addAndMakeVisible(*webView);\n\n'
  readme += '    // Load the UI from resources\n'
  readme += '    auto resourceDir = juce::File::getSpecialLocation(\n'
  readme += '        juce::File::currentApplicationFile\n'
  readme += '    ).getChildFile("Contents/Resources/WebUI");\n\n'
  readme += '    webView->goToURL(resourceDir.getChildFile("index.html").getFullPathName());\n'
  readme += '}\n\n'
  readme += 'void YourPluginEditor::resized()\n'
  readme += '{\n'
  readme += '    webView->setBounds(getLocalBounds());\n'
  readme += '}\n'
  readme += '```\n\n'
  readme += '### 4. Connect Parameter Bindings\n\n'
  readme += bindingsText + '\n\n'
  readme += 'Each control with a `data-parameter-id` attribute needs a corresponding relay:\n\n'
  readme += '```cpp\n'
  readme += '// For each knob/slider:\n'
  readme += 'webSliderRelay->registerSlider("parameterName", [this](float value) {\n'
  readme += '    processor.getParameters().getParameter("parameterName")->setValueNotifyingHost(value);\n'
  readme += '});\n'
  readme += '```\n\n'
  readme += '### 5. Build and Test\n\n'
  readme += '1. Add the WebUI folder to your JUCE project resources\n'
  readme += '2. Build your plugin\n'
  readme += '3. Load in a DAW and verify controls respond\n\n'
  readme += '## Parameter Mapping\n\n'
  readme += 'The following elements have parameter bindings:\n\n'
  readme += '| Element | Parameter ID | Type |\n'
  readme += '|---------|--------------|------|\n'
  readme += parameterRows + '\n\n'
  readme += formatKnownIssuesMarkdown() + '\n\n'
  readme += '## Troubleshooting\n\n'
  readme += '### Controls don\'t respond\n'
  readme += '- Verify parameter IDs match between HTML and C++\n'
  readme += '- Check browser console for JavaScript errors\n'
  readme += '- Ensure WebSliderRelay is properly initialized\n\n'
  readme += '### UI doesn\'t appear\n'
  readme += '- Check file paths are correct\n'
  readme += '- Verify WebView2 runtime is installed (Windows)\n'
  readme += '- Check JUCE WebBrowserComponent is added and visible\n\n'
  readme += '### Visual glitches\n'
  readme += '- Set WebView background color to match your CSS\n'
  readme += '- Use `font-display: swap` for custom fonts\n'
  readme += '- Avoid complex CSS animations during parameter updates\n\n'
  readme += '---\n\n'
  readme += '*Generated by [VST3 WebView UI Designer](https://github.com/your-repo)*\n'

  return readme
}
