/**
 * JavaScript code generator for JUCE WebView2 bindings
 * Generates bindings.js, components.js, and mock JUCE backend
 */

import type { ElementConfig } from '../../types/elements'
import { toKebabCase, toCamelCase } from './utils'
import { isInteractiveElement } from './validators'

// ============================================================================
// Types
// ============================================================================

export interface JSGeneratorOptions {
  isPreviewMode: boolean // true = include mock, false = expect real JUCE
}

// ============================================================================
// Bindings Generator
// ============================================================================

/**
 * Generate bindings.js content
 * Creates JUCE backend listeners for interactive elements (knob, slider, button)
 *
 * @param elements - Array of element configurations
 * @param options - Generation options (preview mode, etc.)
 * @returns JavaScript code as string
 *
 * @example
 * const bindingsJS = generateBindingsJS(elements, { isPreviewMode: false })
 * // Generates window.__JUCE__.backend listeners for each interactive element
 */
export function generateBindingsJS(
  elements: ElementConfig[],
  _options: JSGeneratorOptions
): string {
  const interactiveElements = elements.filter(isInteractiveElement)

  // Generate bindings for each interactive element
  const bindings = interactiveElements
    .map((element) => {
      const varName = toCamelCase(element.name)
      const id = toKebabCase(element.name)

      if (element.type === 'button') {
        // Button pattern: getToggleState
        return `// ${element.name} (${element.type})
const ${varName}State = window.__JUCE__.backend.getToggleState('${id}');
${varName}State.addListener(() => {
  const pressed = ${varName}State.getToggleState();
  updateElementPressed('${id}', pressed);
});`
      } else {
        // Knob/Slider pattern: getSliderState
        return `// ${element.name} (${element.type})
const ${varName}State = window.__JUCE__.backend.getSliderState('${id}');
${varName}State.valueChangedEvent.addListener(() => {
  const value = ${varName}State.getNormalisedValue();
  updateElementValue('${id}', value);
});`
      }
    })
    .join('\n\n')

  // Assemble bindings.js
  return `// ============================================================================
// JUCE WebView2 Bindings
// Generated by VST3 WebView UI Designer
// ============================================================================

// Wait for DOM ready
document.addEventListener('DOMContentLoaded', () => {
  console.log('Initializing JUCE WebView2 bindings...');

${bindings ? '  ' + bindings.replace(/\n/g, '\n  ') : '  // No interactive elements'}

  console.log('JUCE WebView2 bindings initialized');
});
`
}

// ============================================================================
// Components Generator
// ============================================================================

/**
 * Generate components.js content
 * Creates UI update functions for elements
 *
 * @param elements - Array of element configurations
 * @returns JavaScript code as string
 *
 * @example
 * const componentsJS = generateComponentsJS(elements)
 * // Generates updateElementValue and updateElementPressed functions
 */
export function generateComponentsJS(_elements: ElementConfig[]): string {
  return `// ============================================================================
// UI Component Update Functions
// Generated by VST3 WebView UI Designer
// ============================================================================

/**
 * Update element value display (knob, slider, meter)
 * @param {string} id - Element ID (kebab-case)
 * @param {number} value - Normalized value (0-1)
 */
function updateElementValue(id, value) {
  const element = document.getElementById(id);
  if (!element) {
    console.warn(\`Element not found: \${id}\`);
    return;
  }

  // Update data attribute for CSS/JS access
  element.setAttribute('data-value', value);

  // Type-specific updates
  if (element.classList.contains('knob')) {
    updateKnobVisual(element, value);
  } else if (element.classList.contains('slider')) {
    updateSliderVisual(element, value);
  } else if (element.classList.contains('meter')) {
    updateMeterVisual(element, value);
  }
}

/**
 * Update button pressed state
 * @param {string} id - Element ID (kebab-case)
 * @param {boolean} pressed - Whether button is pressed
 */
function updateElementPressed(id, pressed) {
  const element = document.getElementById(id);
  if (!element) {
    console.warn(\`Element not found: \${id}\`);
    return;
  }

  // Update pressed state
  if (pressed) {
    element.classList.add('pressed');
  } else {
    element.classList.remove('pressed');
  }
}

// ============================================================================
// Type-Specific Visual Update Helpers
// ============================================================================

function updateKnobVisual(element, value) {
  // Update rotation or arc fill based on knob style
  // Implementation depends on exported HTML structure
  const indicator = element.querySelector('.knob-indicator');
  if (indicator) {
    const angle = -135 + (270 * value); // -135° to +135°
    indicator.style.transform = \`rotate(\${angle}deg)\`;
  }
}

function updateSliderVisual(element, value) {
  // Update thumb position and track fill
  const thumb = element.querySelector('.slider-thumb');
  const fill = element.querySelector('.slider-fill');

  if (element.classList.contains('vertical')) {
    if (thumb) thumb.style.bottom = \`\${value * 100}%\`;
    if (fill) fill.style.height = \`\${value * 100}%\`;
  } else {
    if (thumb) thumb.style.left = \`\${value * 100}%\`;
    if (fill) fill.style.width = \`\${value * 100}%\`;
  }
}

function updateMeterVisual(element, value) {
  // Update meter fill level
  const fill = element.querySelector('.meter-fill');

  if (element.classList.contains('vertical')) {
    if (fill) fill.style.height = \`\${value * 100}%\`;
  } else {
    if (fill) fill.style.width = \`\${value * 100}%\`;
  }
}
`
}

// ============================================================================
// Mock JUCE Backend Generator
// ============================================================================

/**
 * Generate mock JUCE backend for HTML preview mode
 * Allows standalone testing without JUCE runtime
 *
 * @returns JavaScript code as string
 *
 * @example
 * const mockJS = generateMockJUCE()
 * // Include in <script> tag for HTML preview
 */
export function generateMockJUCE(): string {
  return `// ============================================================================
// Mock JUCE Backend for Standalone Preview
// DO NOT include this in JUCE WebView2 plugin - only for HTML preview
// ============================================================================

if (typeof window.__JUCE__ === 'undefined') {
  console.log('Mock JUCE backend initialized (preview mode)');

  window.__JUCE__ = window.__JUCE__ || {};
  window.__JUCE__.backend = {
    /**
     * Get slider state (for knobs and sliders)
     * @param {string} id - Element ID
     * @returns Mock slider state object
     */
    getSliderState: (id) => {
      let value = 0.5; // Default to center
      const listeners = [];

      return {
        getNormalisedValue: () => value,
        setNormalisedValue: (v) => {
          value = Math.max(0, Math.min(1, v)); // Clamp 0-1
          listeners.forEach(listener => listener());
        },
        valueChangedEvent: {
          addListener: (fn) => listeners.push(fn)
        }
      };
    },

    /**
     * Get toggle button state
     * @param {string} id - Element ID
     * @returns Mock toggle state object
     */
    getToggleState: (id) => {
      let toggled = false;
      const listeners = [];

      return {
        getToggleState: () => toggled,
        setToggleState: (v) => {
          toggled = Boolean(v);
          listeners.forEach(listener => listener());
        },
        addListener: (fn) => listeners.push(fn)
      };
    }
  };

  // Add test controls for interactive preview
  window.addEventListener('DOMContentLoaded', () => {
    console.log('Mock JUCE backend ready - use console to test:');
    console.log('  window.__JUCE__.backend.getSliderState("element-id").setNormalisedValue(0.75)');
    console.log('  window.__JUCE__.backend.getToggleState("button-id").setToggleState(true)');
  });
}
`
}
